#!/bin/bash

function recon {
    cd output_images;
    SECONDS=0;
    echo running $1 >> log;
    ../worm --z $1 --edgePower -1 --useAlternate true --saveSeeds true --saveDists true --maxDistance 80 --blur 7 --saveProbs true --showSeeds true;
    echo took $SECONDS seconds >> log;
    echo >> log;
    cd ..;
}

recon 259
echo "
recon 503
recon 504
recon 505
recon 506
recon 507
recon 508
recon 509
recon 510
recon 511
recon 512
recon 513
recon 514
"
